#include <stdio.h>
#include <stdlib.h>

#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <libavfilter/buffersink.h>
#include <libavfilter/buffersrc.h>
#include <libavutil/mem.h>
#include <libavutil/opt.h>
#include <libavutil/time.h>


//SOURCES FOR THIS: https://wiki.multimedia.cx/index.php/FFmpeg_filter_HOWTO?utm_source=chatgpt.com
//https://ffmpeg.org/ffmpeg-filters.html#Filtering-Introduction
//https://www.ffmpeg.org/doxygen/trunk/group__lavfi.html
//https://readoss.com/en/FFmpeg/FFmpeg/ffmpeg-filter-graph-engine-libavfilter?utm_source=chatgpt.com#format-negotiation-between-filters
//https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/decode_filter_video.c#L100
const char *in = "input.webm";
const char *out = "output.mkv";

const char *filter_descr = "gblur=sigma=3";
static AVFormatContext *fmt_ctx;
//THIS IS THE NEW OUTPUT FORMAT CONTEXT. JUST LIKE fmt_ctx IS THE MANIFEST FOR READING THE INPUT BOX, out_fmt_ctx IS THE MANIFEST FOR WRITING THE OUTPUT BOX. IT HOLDS ALL THE INFORMATION ABOUT THE OUTPUT CONTAINER, WHAT STREAMS IT WILL HAVE, WHAT FORMAT IT WILL USE, AND IT HANDLES THE ACTUAL WRITING OF BYTES TO DISK. WITHOUT THIS, THE PROGRAM HAS NO IDEA WHERE TO PUT THE FRAMES AFTER FILTERING.
static AVFormatContext *out_fmt_ctx;
static AVCodecContext *dec_ctx;
//THIS IS THE NEW ENCODER CONTEXT. THE DECODER CONTEXT dec_ctx IS RESPONSIBLE FOR TAKING COMPRESSED PACKETS AND TURNING THEM INTO RAW FRAMES. THE ENCODER CONTEXT enc_ctx IS THE EXACT OPPOSITE. IT TAKES THE RAW FILTERED FRAMES THAT COME OUT OF THE FILTER GRAPH AND COMPRESSES THEM BACK INTO PACKETS THAT CAN ACTUALLY BE WRITTEN TO A FILE.
static AVCodecContext *enc_ctx;
//THIS IS THE OUTPUT STREAM. JUST LIKE THE INPUT FILE HAS STREAMS INSIDE IT (fmt_ctx->streams[video_stream_index]), THE OUTPUT FILE ALSO NEEDS AT LEAST ONE STREAM TO HOLD THE VIDEO DATA. out_stream IS THE SLOT WE CREATE INSIDE out_fmt_ctx TO HOLD OUR ENCODED VIDEO.
static AVStream *out_stream;
//BUFFER SINK IS THE LAST FILTER THAT IS RESPONSIBLE FOR COLLECTING ALL THE PROCESSED FRAMES AND THUS IT HAS NO OUTPUT PAD, ONLY INPUT PADS.
AVFilterContext *buffersink_ctx;
// BUFFER SRC OR SOURCE IS THE FIRST FILTER THAT RECIEVES THE FIRST INPUT FRAMES.
AVFilterContext *buffersrc_ctx;
//AV FILTER GRAPH IS THE WRAPPER OR THE MAIN STRUCUTRE THAT HOLDS ALL THE FILTERS, LINKS, BUFFER SRC AND BUFFER SINK.
AVFilterGraph *filter_graph;
static int video_stream_index = -1;

static int open_input_file(const char *filename){
    //DECODER
    const AVCodec *decoder;
    //THIS IS THE RETURN VARIABLE, MOST OF THE FUNCTIONS IN THE C API OF FFMPEG HAVE A RETURN VALUE, AND UNTIL NOW I HAVE BEEN USING THEM WITHOUT CHECKING OR VERIFIYING WHAT THIS RETURN VALUE IS RETURNNING, IT IS IMPORTANT TO ALWAYS CHECK THIS RETURN VALUE AS IT HELPS IN PREVENTING MEMORY LEAKS, MEMROY CORRUPTION, AND ACTS AS THE SIMPLEST GUARD RAIL INCASE SOME FUNCTION IS BEING CALLED INCORRECTLY OR IF THE DESIRED DATA DOESN'T EXIST.
    int ret;
    //THIS IS HOW WE ARE GOING TO UTILISE THE RETURN VARIABLE, BY CHECKING THAT THE RETURN VALUE IS GREATER THAN 0 IN ORDER TO MAKE SURE THAT THE FUNCTIONS ARE WORKING PROPERLY AND IN CASE THEY ARE FAILING, WE KNOW WHY AND WHICH ONE.
    if((ret = avformat_open_input(&fmt_ctx, filename, 0, 0)) < 0){
        av_log(NULL, AV_LOG_ERROR, "Cannot open input file\n");
        return ret;
    } 
    if((ret = avformat_find_stream_info(fmt_ctx, 0)) < 0){
        av_log(NULL, AV_LOG_ERROR, "Cannot find the streams in input file\n");
        return ret;
    }
    //IN THIS PARTICULAR CODE EXAMPLE WE ARE GOING TO TRY TO CHANGE THE VIDEO SCALE, BASICALLY RESCALE THE VIDEO FROM 1920X1080 TO SOMEHTING ELSE, SO WE NATUARALLY NEED THE VIDEO STREAM, WE USE av_find_best_stream, THIS FUNCTION CAN FIND STREAMS BASED ON 
    ret = av_find_best_stream(fmt_ctx, AVMEDIA_TYPE_VIDEO, -1, -1, &decoder, 0);
    if (ret < 0) {
        av_log(NULL, AV_LOG_ERROR, "Cannot find a video stream in the input file\n");
        return ret;
    }
    //NOW WE CAN SET THE RETURNED VALUE OF THE STREAM FINDER FUNCTION TO OUR RETURN VARIABLE
    video_stream_index = ret;

    //CREATING THE DECODER CONTEXT
    dec_ctx = avcodec_alloc_context3(decoder);
    //COPYING THE DECODER'S PARAMETER INTO THE CODEC CONTEXT FROM THE AVCodecParameters STRCUTURE, THE avcodec_alloc_context3 IS JUST FOR ALLOCATING THE CONTEXT MEMEORY, THE FOLLOWING FUNCTION IS ACTUALLY COPYING THE VALUES FROM THE PARAMETERS STRUCUTRE. 
    avcodec_parameters_to_context(dec_ctx, fmt_ctx->streams[video_stream_index]->codecpar);
    // NOW WE ARE GOING TO INTIALISE THE DECODER BY OPENING AN I/O STREAM USING avcodec_open2()
    if((ret = avcodec_open2(dec_ctx, decoder, NULL)) <0){
        av_log(NULL, AV_LOG_ERROR, "Cannot open decoder\n");
        return ret;
    }
    return 0;
}

static void init_filters(const char *filter_descr){
    //THIS STRING IS GOING TO HOLD THE ARGUMENTS THAT WE PASS INTO THE BUFFER SOURCE FILTER, THE BUFFER SOURCE NEEDS TO KNOW WHAT KIND OF FRAMES IT IS GOING TO BE RECIEVING SO THAT IT CAN CORRECTLY PASS THEM DOWN THE FILTER CHAIN. THINGS LIKE THE WIDTH, HEIGHT, PIXEL FORMAT, TIMEBASE, AND ASPECT RATIO ARE ALL PROPERTIES OF THE RAW DECODED FRAMES THAT ARE COMING OUT OF OUR DECODER.
    char args[512];

    //GETTING THE ACTUAL FILTER STRUCTS BY THEIR STRING NAMES, avfilter_get_by_name() SIMPLY LOOKS UP THE GLOBALLY REGISTERED FILTER TABLE INSIDE FFMPEG AND RETURNS A POINTER TO THAT FILTER'S DEFINITION. IT IS NOT CREATING ANYTHING YET, IT IS JUST FINDING THE BLUEPRINT.
    const AVFilter *buffersource = avfilter_get_by_name("buffer");
    const AVFilter *buffersink = avfilter_get_by_name("buffersink");

    //AVFilterInOut is very essential for the working of function avfilter_graph_parse_ptr(), WHEN WE PARSE THE STRING INTO THE FILTERS, OUR PROGRAM NEEDS TO KNOW WHETHER THAT THE PARSING THAT WE ARE DOING IS FOR INPUT OR OUTPUT, INPUTS AND OUTPUTS ACT LIKE LABELS FOR THIS EXACT PURPOSE.
    AVFilterInOut *inputs = avfilter_inout_alloc();
    AVFilterInOut *outputs = avfilter_inout_alloc();
    //KEEPING THE ORIGINAL TIMEBASE FOR FUTURE USE CASE;
    AVRational time_base = fmt_ctx->streams[video_stream_index]->time_base;

    //FINALLY ALLOCATING THE FILTER GRAPH
    filter_graph = avfilter_graph_alloc();

    //NOW WE BUILD THE args STRING THAT DESCRIBES THE PROPERTIES OF THE FRAMES THAT WILL BE FED INTO THE BUFFER SOURCE. THIS IS BASICALLY TELLING THE FIRST FILTER IN THE CHAIN HOW THE FRAMES ARE GOING TO LOOK LIKE. THE WIDTH AND HEIGHT COME FROM THE DECODER CONTEXT BECAUSE THAT IS WHERE WE ALREADY PARSED AND STORED THE VIDEO PROPERTIES. pix_fmt IS AN INTEGER ENUM THAT TELLS FFMPEG WHAT COLOR SPACE AND BIT DEPTH THE RAW FRAMES ARE IN, FOR EXAMPLE YUV420P OR RGB24. TIME_BASE IS THE UNIT OF TIME WE ARE USING TO MEASURE TIMESTAMPS THIS IS WHAT WE STORED THE TIME BASE FOR PREVIOUSLY.
    snprintf(args, sizeof(args),
         "video_size=%dx%d:pix_fmt=%d:time_base=%d/%d:pixel_aspect=%d/%d",
         dec_ctx->width, dec_ctx->height, dec_ctx->pix_fmt,
         time_base.num, time_base.den,
         dec_ctx->sample_aspect_ratio.num, dec_ctx->sample_aspect_ratio.den);
    
    //CREATING THE ACTUAL NODE/GRAPH THAT WAS INTIALISED BY THE avfilter_get_by_name() function. avfilter_graph_create_filter() DOES THREE THINGS AT ONCE: IT ALLOCATES A NEW AVFilterContext, IT INITIALISES IT USING THE AVFilter BLUEPRINT WE FOUND EARLIER, AND IT REGISTERS THAT NEW CONTEXT INSIDE THE filter_graph SO THE GRAPH KNOWS IT EXISTS. THE "in" STRING IS JUST A NAME/LABEL WE GIVE THIS PARTICULAR INSTANCE OF THE FILTER SO WE CAN REFER TO IT LATER. THE args STRING WE JUST BUILT IS PASSED HERE SO THE BUFFER SOURCE KNOWS EXACTLY WHAT KIND OF FRAMES TO EXPECT.
    avfilter_graph_create_filter(&buffersrc_ctx, buffersource, "in", args, NULL, filter_graph);

    //ALLOCATING THE CONTEXT FOR THAT NEWLY FORMED SINK FILTER. NOTICE THAT FOR THE SINK WE ARE USING avfilter_graph_alloc_filter() INSTEAD OF avfilter_graph_create_filter(). THE DIFFERENCE IS THAT avfilter_graph_alloc_filter() ONLY ALLOCATES AND REGISTERS THE CONTEXT IN THE GRAPH BUT DOES NOT INITIALISE IT YET. WE DO THIS BECAUSE WE WANT TO SET SOME OPTIONS ON THE SINK BEFORE INITIALISING IT, AND YOU CANNOT SET OPTIONS AFTER INITIALISATION. avfilter_graph_create_filter() WOULD DO ALLOCATION AND INITIALISATION IN ONE SHOT WHICH WOULD NOT GIVE US THAT WINDOW TO SET OPTIONS.
    buffersink_ctx = avfilter_graph_alloc_filter(filter_graph, buffersink, "out");

    //NOW WE INITIALISE THE SINK WITH avfilter_init_dict() PASSING NULL BECAUSE WE HAVE NO ADDITIONAL OPTIONS TO SET IN THIS SIMPLE CASE. IN THE OFFICIAL FFMPEG EXAMPLE THEY SET A PIXEL FORMAT OPTION ON THE SINK BEFORE THIS CALL USING av_opt_set(), WHICH FORCES THE OUTPUT FRAMES TO BE IN A SPECIFIC FORMAT LIKE GRAYSCALE. WE ARE SKIPPING THAT HERE BECAUSE WE JUST WANT THE SCALED OUTPUT IN WHATEVER FORMAT THE SCALE FILTER NATURALLY PRODUCES.
    avfilter_init_dict(buffersink_ctx, NULL);


    //NOT UNDERSTANDING THIS
    //OH so my application is first taking the frames out, like we do in any other video processing code, label them as in  or input send it to the string filter, the filter does it's thing, returns it to us as output but now it is like the input for our application??
    //NOW COMES THE MOST CONFUSING PART OF THE ENTIRE FILTER SETUP. WE HAVE TWO AVFilterInOut STRUCTS CALLED inputs AND outputs AND AT FIRST GLANCE IT SEEMS LIKE WE ARE ASSIGNING THEM COMPLETELY BACKWARDS. WE ARE SETTING outputs TO POINT TO THE BUFFER SOURCE (WHICH IS THE INPUT SIDE) AND WE ARE SETTING inputs TO POINT TO THE BUFFER SINK (WHICH IS THE OUTPUT SIDE). THIS IS NOT A BUG. THE NAMING IS FROM THE PERSPECTIVE OF THE FILTER DESCRIPTION STRING, NOT FROM THE PERSPECTIVE OF OUR PROGRAM. THE outputs STRUCT REPRESENTS THE OUTPUT END OF OUR ALREADY CREATED NODES THAT NEEDS TO BE CONNECTED TO THE INPUT OF THE FILTER STRING. THE inputs STRUCT REPRESENTS THE INPUT END OF OUR ALREADY CREATED NODES THAT NEEDS TO RECEIVE THE OUTPUT OF THE FILTER STRING. IN OTHER WORDS: THE BUFFER SOURCE IS A NODE THAT FEEDS DATA OUT INTO THE FILTER STRING, SO IT IS THE "OUTPUT" SIDE OF OUR PRE-BUILT NODES. THE BUFFER SINK IS A NODE THAT RECEIVES DATA FROM THE FILTER STRING, SO IT IS THE "INPUT" SIDE OF OUR PRE-BUILT NODES. avfilter_graph_parse_ptr() WILL USE THESE TWO STRUCTS AS ANCHOR POINTS TO CONNECT EACH END OF THE PARSED FILTER CHAIN.
    outputs->name = av_strdup("in");
    outputs->filter_ctx = buffersrc_ctx;
    outputs->pad_idx = 0;
    outputs->next = NULL;

    inputs->name = av_strdup("out");
    inputs->filter_ctx = buffersink_ctx;
    inputs->pad_idx = 0;
    inputs->next = NULL;

    //avfilter_graph_parse_ptr() IS THE FUNCTION THAT ACTUALLY READS OUR filter_descr STRING LIKE "scale=400:3200" AND CREATES ALL THE INTERMEDIATE FILTER NODES AND LINKS THEM TOGETHER INSIDE THE filter_graph. IT USES THE inputs AND outputs STRUCTS WE JUST SET UP TO KNOW HOW TO CONNECT THE TWO ENDS OF THAT PARSED CHAIN TO OUR BUFFERSRC AND BUFFERSINK NODES. AFTER THIS CALL THE ENTIRE PIPELINE EXISTS AS A CONNECTED GRAPH IN MEMORY BUT IT HAS NOT BEEN VALIDATED YET.
    avfilter_graph_parse_ptr(filter_graph, filter_descr, &inputs, &outputs, NULL);

    //avfilter_graph_config() IS THE VALIDATION AND FINALISATION STEP. IT WALKS THROUGH THE ENTIRE GRAPH WE JUST BUILT AND CHECKS THAT EVERY CONNECTION IS COMPATIBLE, FOR EXAMPLE THAT PIXEL FORMATS MATCH OR CAN BE CONVERTED, THAT ALL PADS ARE CONNECTED, AND THAT THERE ARE NO BROKEN LINKS. IT ALSO NEGOTIATES THE FORMAT BETWEEN ALL THE CONNECTED FILTERS SO THAT EACH FILTER KNOWS EXACTLY WHAT IT WILL RECEIVE AND WHAT IT MUST OUTPUT. WITHOUT THIS CALL THE GRAPH IS JUST A STRUCTURE IN MEMORY WITH NO GUARANTEES THAT IT WILL ACTUALLY WORK WHEN WE TRY TO PUSH FRAMES THROUGH IT.
    avfilter_graph_config(filter_graph, NULL);

    //WE ALWAYS FREE THE AVFilterInOut STRUCTS AFTER PARSING BECAUSE avfilter_graph_parse_ptr() HAS ALREADY USED THEM TO WIRE UP THE CONNECTIONS INSIDE THE GRAPH. THE GRAPH ITSELF NOW OWNS ALL THOSE INTERNAL LINKS, SO THESE TEMPORARY HELPER STRUCTS ARE NO LONGER NEEDED AND HOLDING ONTO THEM WOULD JUST BE A MEMORY LEAK.
    avfilter_inout_free(&inputs);
    avfilter_inout_free(&outputs);
}

//THIS IS THE BRAND NEW FUNCTION THAT WAS COMPLETELY MISSING FROM THE ORIGINAL CODE AND IS THE REASON THE OUTPUT FILE NEVER CHANGED. open_output_file() SETS UP EVERYTHING NEEDED TO WRITE THE FILTERED VIDEO TO DISK. IT HAS THREE JOBS: FIRST, CREATE THE OUTPUT CONTAINER (THE BOX THAT WILL HOLD THE VIDEO). SECOND, SET UP AN H.264 ENCODER TO COMPRESS THE RAW FILTERED FRAMES. THIRD, OPEN THE ACTUAL FILE ON DISK AND WRITE THE CONTAINER HEADER. THIS FUNCTION MUST BE CALLED AFTER init_filters() BECAUSE IT NEEDS TO QUERY THE BUFFERSINK TO FIND OUT WHAT WIDTH, HEIGHT, AND PIXEL FORMAT THE FILTER IS GOING TO PRODUCE. IF YOU CALL IT BEFORE THE FILTER GRAPH IS CONFIGURED, THE SINK DOES NOT KNOW ITS OWN OUTPUT PROPERTIES YET.
static int open_output_file(void){
    int ret;

    //avcodec_find_encoder() LOOKS UP THE GLOBALLY REGISTERED ENCODER TABLE INSIDE FFMPEG AND RETURNS A POINTER TO THE H.264 ENCODER DEFINITION. THIS IS THE SAME CONCEPT AS avfilter_get_by_name() OR av_find_best_stream() WITH &decoder, IT IS JUST FINDING THE BLUEPRINT, NOT CREATING ANYTHING YET. WE ARE CHOOSING H.264 BECAUSE IT IS THE MOST UNIVERSALLY SUPPORTED VIDEO CODEC AND IT WORKS PERFECTLY INSIDE AN MKV CONTAINER.
    const AVCodec *encoder = avcodec_find_encoder(AV_CODEC_ID_H264);
    if(!encoder){
        av_log(NULL, AV_LOG_ERROR, "H.264 encoder not found\n");
        return AVERROR_ENCODER_NOT_FOUND;
    }

    //avformat_alloc_output_context2() IS THE OUTPUT EQUIVALENT OF avformat_open_input(). WHERE avformat_open_input() OPENS AN EXISTING FILE AND READS ITS MANIFEST, THIS FUNCTION CREATES A BRAND NEW EMPTY MANIFEST FOR A FILE WE ARE ABOUT TO CREATE. WE PASS NULL FOR THE FORMAT BECAUSE WE WANT FFMPEG TO AUTOMATICALLY DETECT THE RIGHT CONTAINER FORMAT FROM THE FILENAME EXTENSION. SINCE OUR FILENAME ENDS IN .mkv, FFMPEG WILL AUTOMATICALLY SET UP THE MATROSKA CONTAINER FORMAT RULES INSIDE out_fmt_ctx.
    if((ret = avformat_alloc_output_context2(&out_fmt_ctx, NULL, NULL, out)) < 0){
        av_log(NULL, AV_LOG_ERROR, "Cannot create output context\n");
        return ret;
    }

    //avformat_new_stream() ADDS A NEW EMPTY STREAM SLOT TO THE OUTPUT CONTAINER. THINK OF THE CONTAINER AS A BOX AND THIS FUNCTION AS CREATING A NEW LABELED COMPARTMENT INSIDE THAT BOX SPECIFICALLY FOR VIDEO. THE STREAM IS EMPTY AT THIS POINT, IT HAS NO CODEC INFORMATION YET. WE WILL FILL IT IN AFTER WE CONFIGURE THE ENCODER. WE STORE THE POINTER IN out_stream BECAUSE WE NEED TO REFERENCE IT LATER WHEN WRITING PACKETS AND WHEN RESCALING TIMESTAMPS.
    out_stream = avformat_new_stream(out_fmt_ctx, NULL);
    if(!out_stream){
        av_log(NULL, AV_LOG_ERROR, "Cannot create output stream\n");
        return AVERROR_UNKNOWN;
    }

    //NOW WE ALLOCATE THE ENCODER CONTEXT. THIS IS THE SAME PATTERN AS THE DECODER: avcodec_alloc_context3() JUST ALLOCATES THE MEMORY FOR THE CONTEXT STRUCT, IT DOES NOT START THE ENCODER. THINK OF IT AS SETTING UP AN EMPTY SETTINGS PAGE FOR THE ENCODER WHERE WE WILL FILL IN ALL THE REQUIRED PARAMETERS BEFORE TURNING IT ON.
    enc_ctx = avcodec_alloc_context3(encoder);
    if(!enc_ctx){
        av_log(NULL, AV_LOG_ERROR, "Cannot allocate encoder context\n");
        return AVERROR(ENOMEM);
    }

    //NOW WE CONFIGURE THE ENCODER BY QUERYING THE BUFFERSINK DIRECTLY. THIS IS THE KEY INSIGHT: AFTER avfilter_graph_config() HAS BEEN CALLED IN init_filters(), THE BUFFERSINK KNOWS EXACTLY WHAT IT IS GOING TO OUTPUT. SO INSTEAD OF HARDCODING VALUES LIKE 1280 AND 720, WE ASK THE SINK WHAT IT WILL ACTUALLY PRODUCE. THIS WAY IF YOU CHANGE filter_descr TO A DIFFERENT SCALE, THE ENCODER AUTOMATICALLY ADJUSTS WITHOUT YOU NEEDING TO CHANGE ANYTHING ELSE.
    //av_buffersink_get_w() AND av_buffersink_get_h() RETURN THE WIDTH AND HEIGHT OF THE FRAMES THE SINK WILL OUTPUT, IN OUR CASE 1280 AND 720.
    enc_ctx->width   = av_buffersink_get_w(buffersink_ctx);
    enc_ctx->height  = av_buffersink_get_h(buffersink_ctx);
    //av_buffersink_get_format() RETURNS THE PIXEL FORMAT AS AN INTEGER ENUM. FOR OUR VP9 INPUT GOING THROUGH THE SCALE FILTER, THIS WILL BE AV_PIX_FMT_YUV420P WHICH IS THE STANDARD FORMAT THAT H.264 EXPECTS.
    enc_ctx->pix_fmt = av_buffersink_get_format(buffersink_ctx);
    //av_buffersink_get_time_base() RETURNS THE TIME UNIT THE SINK WILL USE TO STAMP EACH FRAME. SETTING THE SAME TIMEBASE ON THE ENCODER ENSURES THAT WHEN WE FEED FRAMES INTO THE ENCODER, THEIR TIMESTAMPS ARE ALREADY IN THE UNIT THE ENCODER UNDERSTANDS WITHOUT ANY CONVERSION.
    enc_ctx->time_base = av_buffersink_get_time_base(buffersink_ctx);
    //av_buffersink_get_frame_rate() RETURNS THE FRAMERATE OF THE VIDEO. THIS IS IMPORTANT FOR THE ENCODER BECAUSE H.264 NEEDS TO KNOW HOW MANY FRAMES PER SECOND IT IS ENCODING IN ORDER TO CALCULATE THINGS LIKE KEYFRAME INTERVALS CORRECTLY.
    enc_ctx->framerate = av_buffersink_get_frame_rate(buffersink_ctx);

    //SOME OUTPUT CONTAINER FORMATS REQUIRE THE CODEC CONFIGURATION DATA TO BE STORED IN ONE CENTRAL PLACE AT THE BEGINNING OF THE FILE RATHER THAN REPEATED INSIDE EVERY SINGLE PACKET. THIS IS CALLED A GLOBAL HEADER. THE AVFMT_GLOBALHEADER FLAG ON THE OUTPUT FORMAT TELLS US IF THIS CONTAINER REQUIRES IT. IF IT DOES, WE SET AV_CODEC_FLAG_GLOBAL_HEADER ON THE ENCODER SO IT KNOWS TO PRODUCE THAT DATA SEPARATELY RATHER THAN EMBEDDING IT IN EVERY PACKET. FOR MKV THIS IS TYPICALLY NOT REQUIRED BUT IT IS ALWAYS GOOD PRACTICE TO CHECK.
    if(out_fmt_ctx->oformat->flags & AVFMT_GLOBALHEADER)
        enc_ctx->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;

    //NOW WE ACTUALLY START THE ENCODER ENGINE. BEFORE THIS CALL enc_ctx IS JUST A CONFIG STRUCT FULL OF SETTINGS. AFTER THIS CALL IT IS A LIVE ENCODER READY TO ACCEPT RAW FRAMES AND PRODUCE COMPRESSED PACKETS. THIS IS THE SAME CONCEPT AS avcodec_open2() FOR THE DECODER.
    if((ret = avcodec_open2(enc_ctx, encoder, NULL)) < 0){
        av_log(NULL, AV_LOG_ERROR, "Cannot open encoder\n");
        return ret;
    }

    //avcodec_parameters_from_context() IS THE REVERSE OF avcodec_parameters_to_context() THAT WE USED WHEN SETTING UP THE DECODER. WHEN SETTING UP THE DECODER WE COPIED PARAMETERS FROM THE STREAM INTO THE CODEC CONTEXT. NOW WE ARE DOING THE OPPOSITE: COPYING THE ENCODER'S SETTINGS BACK INTO THE OUTPUT STREAM'S codecpar. THIS IS HOW THE OUTPUT CONTAINER KNOWS WHAT CODEC AND WHAT RESOLUTION THE VIDEO IN THIS STREAM WILL USE. WITHOUT THIS THE OUTPUT FILE WOULD HAVE AN EMPTY STREAM WITH NO CODEC INFORMATION AND IT WOULD BE UNPLAYABLE.
    avcodec_parameters_from_context(out_stream->codecpar, enc_ctx);
    //WE ALSO SET THE OUTPUT STREAM'S TIMEBASE TO MATCH THE ENCODER'S TIMEBASE SO THAT THE CONTAINER CORRECTLY INTERPRETS ALL THE TIMESTAMPS WE WILL BE WRITING INTO THE PACKETS.
    out_stream->time_base = enc_ctx->time_base;

    //AVIOCONTEXT IS FFMPEG'S LOW-LEVEL I/O LAYER. IT HANDLES THE ACTUAL BYTE-BY-BYTE WRITING TO DISK, SIMILAR TO HOW fopen() AND fwrite() WORK IN STANDARD C BUT WITH FFMPEG'S OWN BUFFERING AND ERROR HANDLING ON TOP. out_fmt_ctx->pb IS THE POINTER TO THIS I/O CONTEXT. THE AVFMT_NOFILE FLAG CHECK IS THERE BECAUSE SOME SPECIAL FORMAT CONTEXTS (LIKE NETWORK STREAMS) MANAGE THEIR OWN I/O AND DON'T NEED YOU TO OPEN A FILE. FOR A NORMAL FILE LIKE output.mkv THIS FLAG WILL NOT BE SET SO WE ALWAYS ENTER THIS BLOCK.
    if(!(out_fmt_ctx->oformat->flags & AVFMT_NOFILE)){
        if((ret = avio_open(&out_fmt_ctx->pb, out, AVIO_FLAG_WRITE)) < 0){
            av_log(NULL, AV_LOG_ERROR, "Cannot open output file on disk\n");
            return ret;
        }
    }
    //avformat_write_header() WRITES THE CONTAINER HEADER TO THE BEGINNING OF THE OUTPUT FILE. EVERY CONTAINER FORMAT STARTS WITH A HEADER THAT DESCRIBES WHAT STREAMS ARE INSIDE, WHAT CODECS THEY USE, AND OTHER METADATA. FOR MKV THIS INCLUDES THE EBML HEADER AND THE SEGMENT INFORMATION. THIS CALL IS MANDATORY. IF I SKIP IT AND START WRITING PACKETS DIRECTLY THE OUTPUT FILE WILL BE COMPLETELY CORRUPT AND NO PLAYER WILL BE ABLE TO OPEN IT BECAUSE THEY WILL NOT KNOW WHAT IS INSIDE OR HOW TO READ IT.
    if((ret = avformat_write_header(out_fmt_ctx, NULL)) < 0){
        av_log(NULL, AV_LOG_ERROR, "Cannot write output file header\n");
        return ret;
    }

    return 0;
}

//THIS IS THE OTHER BRAND NEW FUNCTION THAT WAS COMPLETELY MISSING. encode_and_write() IS THE BRIDGE BETWEEN THE FILTER GRAPH AND THE OUTPUT FILE. IT TAKES ONE RAW FILTERED FRAME, SENDS IT INTO THE ENCODER, PULLS OUT THE RESULTING COMPRESSED PACKETS, AND WRITES THEM TO DISK. THIS FUNCTION ALSO HANDLES THE FLUSH CASE: WHEN WE PASS NULL AS THE FRAME AT THE END OF THE PROGRAM, THE ENCODER KNOWS THERE IS NOTHING MORE COMING AND IT FLUSHES OUT ALL THE FRAMES IT HAS BEEN HOLDING IN ITS INTERNAL BUFFER. THIS IS CRITICAL FOR H.264 BECAUSE THE ENCODER DELIBERATELY DELAYS OUTPUT BY SEVERAL FRAMES TO ALLOW IT TO LOOK AHEAD AND MAKE BETTER COMPRESSION DECISIONS. IF YOU DO NOT FLUSH, THOSE LAST FEW FRAMES ARE SIMPLY LOST AND THE END OF YOUR VIDEO WILL BE CUT OFF.
static int encode_and_write(AVFrame *filt_frame){
    int ret;

    //WE NEED A FRESH PACKET CONTAINER TO HOLD WHATEVER THE ENCODER PRODUCES. THIS IS THE SAME CONCEPT AS THE packet WE USE IN main() TO HOLD WHAT WE READ FROM THE INPUT FILE, BUT THIS ONE IS FOR THE ENCODED OUTPUT SIDE.
    AVPacket *enc_pkt = av_packet_alloc();
    if(!enc_pkt) return AVERROR(ENOMEM);

    //avcodec_send_frame() IS THE PUSH HALF OF THE ENCODER'S PUSH-PULL PATTERN. WE PUSH ONE RAW FRAME IN. PASSING NULL HERE INSTEAD OF A REAL FRAME IS THE SIGNAL TO THE ENCODER THAT WE ARE DONE SENDING FRAMES AND IT SHOULD FLUSH EVERYTHING IT HAS BEEN BUFFERING INTERNALLY. THIS IS THE EXACT SAME PUSH-PULL PATTERN AS THE DECODER BUT IN REVERSE: THE DECODER RECEIVES COMPRESSED PACKETS AND PRODUCES RAW FRAMES, THE ENCODER RECEIVES RAW FRAMES AND PRODUCES COMPRESSED PACKETS.
    ret = avcodec_send_frame(enc_ctx, filt_frame);
    if(ret < 0){
        av_log(NULL, AV_LOG_ERROR, "Error sending frame to encoder\n");
        av_packet_free(&enc_pkt);
        return ret;
    }

    //avcodec_receive_packet() IS THE PULL HALF. ONE RAW FRAME IN DOES NOT ALWAYS MEAN ONE COMPRESSED PACKET OUT IMMEDIATELY. THE ENCODER BUFFERS MULTIPLE FRAMES INTERNALLY TO MAKE BETTER COMPRESSION DECISIONS, SO WE KEEP PULLING UNTIL IT RETURNS EAGAIN (MEANING GIVE ME MORE FRAMES FIRST) OR EOF (MEANING ALL DONE). THIS IS IDENTICAL IN CONCEPT TO THE while(avcodec_receive_frame()) LOOP WE USE ON THE DECODER SIDE.
    while(avcodec_receive_packet(enc_ctx, enc_pkt) >= 0){

        //av_packet_rescale_ts() CONVERTS ALL THE TIMESTAMPS INSIDE enc_pkt FROM ONE TIME UNIT TO ANOTHER. THE ENCODER WORKS IN ITS OWN TIMEBASE (enc_ctx->time_base) BUT THE OUTPUT STREAM HAS ITS OWN TIMEBASE (out_stream->time_base) WHICH THE CONTAINER USES. THESE TWO FRACTIONS MIGHT NOT BE IDENTICAL, SO THIS FUNCTION MATHEMATICALLY CONVERTS ALL THREE TIMESTAMPS IN THE PACKET (PTS, DTS, AND DURATION) SO THEY REPRESENT THE SAME MOMENT IN TIME BUT MEASURED IN THE OUTPUT STREAM'S UNIT. IF YOU SKIP THIS STEP, YOUR VIDEO WILL PLAY AT THE WRONG SPEED BECAUSE THE CONTAINER WILL MISINTERPRET ALL THE TIMESTAMPS.
        av_packet_rescale_ts(enc_pkt, enc_ctx->time_base, out_stream->time_base);
        //WE MUST TELL THE PACKET WHICH STREAM IT BELONGS TO INSIDE THE OUTPUT FILE. SINCE WE ONLY HAVE ONE STREAM IN OUR OUTPUT, out_stream->index WILL ALWAYS BE 0, BUT IT IS IMPORTANT TO SET THIS CORRECTLY BECAUSE av_interleaved_write_frame() USES IT TO KNOW WHICH STREAM'S RULES TO APPLY WHEN WRITING.
        enc_pkt->stream_index = out_stream->index;

        //av_interleaved_write_frame() IS THE FUNCTION THAT ACTUALLY WRITES THE COMPRESSED PACKET TO THE OUTPUT FILE ON DISK. THE WORD INTERLEAVED MEANS FFMPEG WILL INTERNALLY SORT AND BUFFER PACKETS BY TIMESTAMP IF NECESSARY TO ENSURE THE OUTPUT FILE HAS AUDIO AND VIDEO PACKETS PROPERLY INTERLEAVED IN TIME ORDER. THIS IS IMPORTANT FOR SMOOTH PLAYBACK BECAUSE PLAYERS READ SEQUENTIALLY AND EXPECT AUDIO AND VIDEO TO BE ROUGHLY ALTERNATING, NOT ALL VIDEO FIRST THEN ALL AUDIO. IN OUR CASE WE ONLY HAVE VIDEO SO THE INTERLEAVING DOES NOT MATTER MUCH, BUT IT IS ALWAYS THE RIGHT FUNCTION TO USE FOR WRITING PACKETS.
        ret = av_interleaved_write_frame(out_fmt_ctx, enc_pkt);
        if(ret < 0){
            av_log(NULL, AV_LOG_ERROR, "Error writing packet to output file\n");
            break;
        }
        //UNREF THE PACKET AFTER WRITING IT SO ITS BUFFER MEMORY IS RELEASED AND enc_pkt CAN BE REUSED FOR THE NEXT PACKET THE ENCODER PRODUCES. WITHOUT THIS WE WOULD LEAK THE MEMORY OF EVERY SINGLE COMPRESSED PACKET WE WRITE.
        av_packet_unref(enc_pkt);
    }

    av_packet_free(&enc_pkt);
    return 0;
}

int main(void){
    printf("FFmpeg version: %s\n", av_version_info());
    //THESE ARE THE THREE CORE DATA CONTAINERS WE NEED FOR THE DECODE AND FILTER PIPELINE. packet IS THE COMPRESSED DATA UNIT READ DIRECTLY FROM THE FILE, ONE PACKET TYPICALLY CORRESPONDS TO ONE COMPRESSED FRAME. frame IS THE RAW UNCOMPRESSED FRAME THAT COMES OUT OF THE DECODER AFTER WE FEED IT A PACKET. filt_frame IS THE FRAME THAT COMES OUT OF THE FILTER GRAPH AFTER THE RAW FRAME HAS BEEN PROCESSED, IN OUR CASE AFTER BEING SCALED.
    AVPacket *packet   = av_packet_alloc();
    AVFrame  *frame      = av_frame_alloc();
    AVFrame  *filt_frame = av_frame_alloc();

    int ret;

    //OPENING THE INPUT FILE AND SETTING UP THE DECODER AS WE DISCUSSED IN open_input_file()
    open_input_file(in);

    //BUILDING THE ENTIRE FILTER GRAPH WITH THE BUFFER SOURCE, SCALE FILTER, AND BUFFER SINK ALL LINKED TOGETHER
    init_filters(filter_descr);

    //WE CALL open_output_file() HERE, AFTER init_filters() AND NOT BEFORE. THE ORDER IS DELIBERATE AND MANDATORY. open_output_file() ASKS THE BUFFERSINK WHAT WIDTH, HEIGHT, AND PIXEL FORMAT IT IS GOING TO PRODUCE SO IT CAN CONFIGURE THE ENCODER TO MATCH EXACTLY. IF WE CALLED open_output_file() BEFORE init_filters(), THE FILTER GRAPH WOULD NOT HAVE BEEN CONFIGURED YET AND THE BUFFERSINK WOULD NOT KNOW ITS OWN OUTPUT PROPERTIES, GIVING US GARBAGE VALUES OR A CRASH.
    if(open_output_file() < 0) return 1;

    //THIS IS THE MAIN READ LOOP. av_read_frame() READS ONE PACKET AT A TIME FROM THE FORMAT CONTEXT, MEANING IT READS THE NEXT CHUNK OF COMPRESSED DATA FROM THE FILE. IT RETURNS A NEGATIVE VALUE WHEN THERE ARE NO MORE PACKETS, WHICH IS HOW WE KNOW TO STOP.
    while (av_read_frame(fmt_ctx, packet) >= 0) {

        //SINCE OUR FILE CAN HAVE MULTIPLE STREAMS LIKE AUDIO AND VIDEO, WE ONLY WANT TO PROCESS PACKETS THAT BELONG TO THE VIDEO STREAM WE FOUND EARLIER. PACKETS FROM OTHER STREAMS ARE SIMPLY IGNORED BY SKIPPING TO THE NEXT ITERATION.
        if (packet->stream_index == video_stream_index) {

            //avcodec_send_packet() HANDS THE COMPRESSED PACKET OVER TO THE DECODER. THE DECODER DOES NOT IMMEDIATELY GIVE US A FRAME BACK, IT PUTS THE PACKET INTO ITS INTERNAL QUEUE AND STARTS WORKING ON IT.
            ret = avcodec_send_packet(dec_ctx, packet);
            if (ret < 0) break;

            //avcodec_receive_frame() IS THE PULL HALF. WE KEEP ASKING THE DECODER FOR FINISHED FRAMES UNTIL IT RETURNS EAGAIN MEANING IT NEEDS MORE PACKETS BEFORE IT CAN PRODUCE ANOTHER FRAME.
            while (avcodec_receive_frame(dec_ctx, frame) >= 0) {
                frame->pts = frame->best_effort_timestamp;

                //WE PUSH THE DECODED RAW FRAME INTO THE FILTER GRAPH THROUGH THE BUFFER SOURCE ENTRY GATE. THE KEEP_REF FLAG TELLS THE FILTER GRAPH TO MAKE ITS OWN INTERNAL REFERENCE TO THE FRAME'S DATA BUFFER SO THAT WHEN WE CALL av_frame_unref() ON frame LATER, THE FILTER GRAPH'S COPY IS STILL VALID AND WON'T BE DESTROYED.
                if (av_buffersrc_add_frame_flags(buffersrc_ctx, frame,
                                                 AV_BUFFERSRC_FLAG_KEEP_REF) < 0) {
                    av_log(NULL, AV_LOG_ERROR, "Error feeding filtergraph\n");
                    break;
                }

                //JUST LIKE THE DECODER, THE FILTER GRAPH CAN ALSO BUFFER FRAMES INTERNALLY SO WE DRAIN IT WITH THE SAME PULL PATTERN. WE KEEP PULLING FRAMES OUT OF THE BUFFERSINK UNTIL IT RETURNS EAGAIN OR EOF.
                while (1) {
                    ret = av_buffersink_get_frame(buffersink_ctx, filt_frame);
                    if (ret == AVERROR(EAGAIN) || ret == AVERROR_EOF)
                        break;
                    if (ret < 0)
                        goto end;

                    //THIS IS THE LINE THAT WAS COMPLETELY MISSING IN THE ORIGINAL CODE. BEFORE, filt_frame HELD THE BEAUTIFUL 1280x720 SCALED FRAME AND WE IMMEDIATELY THREW IT AWAY WITH av_frame_unref(). NOW WE PASS IT TO encode_and_write() WHICH SENDS IT INTO THE H.264 ENCODER AND WRITES THE RESULTING COMPRESSED PACKET TO output.mkv ON DISK. THIS ONE LINE IS WHAT CONNECTS THE FILTER GRAPH TO THE OUTPUT FILE AND IS THE ENTIRE REASON THE OUTPUT WAS NEVER CHANGING.
                    encode_and_write(filt_frame);

                    //NOW WE UNREF filt_frame AFTER WE HAVE FINISHED USING IT. av_frame_unref() DOES NOT FREE THE AVFrame STRUCT ITSELF, IT ONLY RELEASES THE REFERENCE TO THE UNDERLYING PIXEL DATA BUFFER SO THAT MEMORY CAN BE REUSED. THE filt_frame POINTER ITSELF IS STILL VALID AND READY TO BE FILLED AGAIN ON THE NEXT CALL TO av_buffersink_get_frame().
                    av_frame_unref(filt_frame);
                }

                //WE UNREF THE DECODED FRAME AFTER THE ENTIRE SINK DRAIN LOOP IS DONE. WE WAIT UNTIL HERE BECAUSE AV_BUFFERSRC_FLAG_KEEP_REF MEANS THE FILTER GRAPH HOLDS ITS OWN REFERENCE TO THE DATA, SO IT IS SAFE TO RELEASE OURS NOW WITHOUT DESTROYING THE FILTER GRAPH'S COPY.
                av_frame_unref(frame);
            }
        }
        //RELEASE THE PACKET'S BUFFER MEMORY SO IT CAN BE REUSED FOR THE NEXT av_read_frame() CALL. WITHOUT THIS WE WOULD LEAK THE COMPRESSED DATA BUFFER OF EVERY SINGLE PACKET WE READ.
        av_packet_unref(packet);
    }

    //AFTER THE MAIN LOOP IS DONE WE HAVE READ AND PROCESSED EVERY PACKET IN THE FILE. BUT REMEMBER THAT THE H.264 ENCODER HOLDS SEVERAL FRAMES IN AN INTERNAL BUFFER TO MAKE BETTER COMPRESSION DECISIONS BY LOOKING AHEAD. WE NEED TO TELL IT WE ARE DONE BY PASSING NULL AS THE FRAME. THIS SIGNALS A FLUSH AND THE ENCODER WILL OUTPUT ALL THOSE INTERNALLY BUFFERED FRAMES AS PACKETS. IF WE SKIP THIS STEP THE LAST SEVERAL SECONDS OF THE VIDEO WILL SIMPLY BE MISSING FROM THE OUTPUT FILE.
    encode_and_write(NULL);

    //av_write_trailer() WRITES THE END OF THE CONTAINER TO THE FILE. SOME FORMATS LIKE MKV AND MP4 WRITE AN INDEX TABLE AT THE VERY END OF THE FILE THAT LISTS WHERE EVERY KEYFRAME IS LOCATED. THIS INDEX IS WHAT ALLOWS VIDEO PLAYERS TO SEEK INSTANTLY TO ANY POINT IN THE VIDEO. WITHOUT THIS CALL THE FILE IS TECHNICALLY INCOMPLETE. SOME PLAYERS WILL REFUSE TO OPEN IT AND OTHERS WILL OPEN IT BUT SEEKING WILL NOT WORK OR WILL BE VERY SLOW.
    av_write_trailer(out_fmt_ctx);

end:
    //CLEANUP --- FREE EVERYTHING WE ALLOCATED. THE ORDER MATTERS, WE FREE THE FILTER GRAPH FIRST BECAUSE IT HOLDS REFERENCES TO CONTEXTS, THEN WE FREE THE CODEC CONTEXTS, THEN WE CLOSE THE FORMAT CONTEXTS, AND FINALLY THE FRAME AND PACKET CONTAINERS.
    avfilter_graph_free(&filter_graph);
    avcodec_free_context(&dec_ctx);
    //WE ALSO FREE THE ENCODER CONTEXT THAT WE ADDED. SAME RULE AS THE DECODER CONTEXT, avcodec_free_context() CLOSES THE CODEC ENGINE AND RELEASES ALL THE MEMORY THE ENCODER WAS USING INTERNALLY FOR ITS BUFFERS AND LOOKUP TABLES.
    avcodec_free_context(&enc_ctx);
    avformat_close_input(&fmt_ctx);
    //FOR THE OUTPUT FORMAT CONTEXT WE HAVE TWO STEPS. FIRST WE CLOSE THE AVIO I/O LAYER WHICH FLUSHES ANY REMAINING BUFFERED BYTES AND CLOSES THE FILE HANDLE ON DISK. THEN WE FREE THE FORMAT CONTEXT STRUCT ITSELF. WE CHECK THE AVFMT_NOFILE FLAG AGAIN JUST LIKE WE DID WHEN OPENING TO MAKE SURE WE ONLY CLOSE AN I/O CONTEXT THAT WE ACTUALLY OPENED.
    if(out_fmt_ctx && !(out_fmt_ctx->oformat->flags & AVFMT_NOFILE))
        avio_closep(&out_fmt_ctx->pb);
    avformat_free_context(out_fmt_ctx);
    av_frame_free(&frame);
    av_frame_free(&filt_frame);
    av_packet_free(&packet);

    return 0;
}